### ISSUE TITLE
PC com configurações baixas

### ISSUE THREAD

**Issue by JoaoFelixx** [SHARENERGY-OFICIAL/desafio-sharenergy-2023-01#10]
Olá, gostaria de saber se posso postar apenas o projeto (sem o video) por conta do meu pc ser bem antigo e fraquinho... o som dele não funciona, eu posso fazer um readme bem detalhadinho ao invés de fazer o video  ?

**Comment by fhlpassis** [comment]
Sim, tudo bem.
