### ISSUE TITLE
Login de usuário

### ISSUE THREAD

**Issue by amorimll** [SHARENERGY-OFICIAL/desafio-sharenergy-2023-01#15]
Boa tarde, queria saber a respeito da página de login e como deve ser feito, é necessário ter uma página de cadastro? Ou é só definir um login fixo, com as credenciais especificadas?

**Comment by fhlpassis** [comment]
É utilizado um login fixo, como descrito no desafio, além da possibilidade de utilizar o "remember me".

**Comment by amorimll** [comment]
Tudo bem, a página de cadastro pode ser considerada como um extra?

**Comment by fhlpassis** [comment]
Sim
