### ISSUE TITLE
Projeto finalizado

### ISSUE THREAD

**Issue by gioivieira** [SHARENERGY-OFICIAL/desafio-sharenergy-2023-01#232]
Bom dia, gostaria de informar que eu já tinha aberto o PR a duas semanas, mas fiz a finalização do projeto ontem dentro do prazo: https://github.com/SHARENERGY-OFICIAL/desafio-sharenergy-2023-01/pull/45. Obrigada!!

**Comment by fhlpassis** [comment]
Tudo bem.
