### ISSUE TITLE
Dúvida a respeito da linguagem.

### ISSUE THREAD

**Issue by luisf-csdev** [SHARENERGY-OFICIAL/desafio-sharenergy-2023-01#41]
Olá!

Gostaria de saber se há algum problema no projeto estar escrito e **JavaScript** ao invés de **TypeScript**. 

Li a respeito das tecnologias que a empresa utiliza e JS está entre elas. 
Tenho mais familiaridade com JS, portanto prefiro trabalhar com esta, mas caso seja preferencial TS, farei a migração sem problemas. 

Grato!

😃🚀

**Comment by fhlpassis** [comment]
Sim, tudo bem.
