### ISSUE TITLE
Dúvidas a respeito da tela dos usuários, gatos e cachorros

### ISSUE THREAD

**Issue by Alfrederson** [SHARENERGY-OFICIAL/desafio-sharenergy-2023-01#5]
- A resposta tem que passar pelo backend ou o frontend pode consultar as APIs diretamente?
- Os usuários obtidos do random user tem que ser colocados dentro do mongo também pra poder fazer a busca pelo nome?
- É esperado que vai ter um container local do mongo pra fazer a parte do CRUD ou isso é a critério do freguês?
- Tem que deixar online, ou basta botar um dockerfile/compose?

**Comment by fhlpassis** [comment]
O frontend pode consultar as APIs diretamente, mas a utilização do backend no processo é bem-vinda
Não é necessário adicionar os usuários do random user no mongodb
Critério do Participante
O ideal é que seja possível executar a aplicação localmente, como o mesmo será feito é a critério do participante, o deploy da aplicação é opcional, mas bem-vindo

**Comment by Alfrederson** [comment]
Vou subir, não sei se vai conseguir rodar com as instruções que eu escrevi. Vou fazer um vídeo demonstrando o funcionamento também. Estou bem ocupado com outros projetos.
