### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by luccasqueiroz7** [SHARENERGY-OFICIAL/desafio-sharenergy-2023-01#72]
No teste pede que "o usuário seja capaz de se autenticar utilizando o username desafiosharenergy e password sh@r3n3rgy".
Criei uma pagina de cadastro para que o usuário possa cadastrar essa conta manualmente.
Mas quero entender uma coisa, o usuário com username "desafiosharenergy" já deve estar criado e possivel de fazer login ou cabe a quem pegar o codigo cria-lo manualmente?

**Comment by Alfrederson** [comment]
Pelo que disseram é a gosto do freguês, mas tecnicamente se a pessoa consegue fazer o crud de clientes, automaticamente consegue fazer essa parte também, então se for só pra demonstrar que é capaz de fazer...

**Comment by fhlpassis** [comment]
Cabe ao participante do desafio encontrar a melhor solução para a resolução do problema.
