### ISSUE TITLE
Banco de dados

### ISSUE THREAD

**Issue by gioivieira** [SHARENERGY-OFICIAL/desafio-sharenergy-2023-01#73]
Boa tarde, tudo bem?

Gostaria de perguntar se ao invés de usar o MongoDB eu poderia realizar o desafio utilizando o MySQL?
Já tenho prática com o MySQL e por haver um prazo para a entrega do desafio isso me ajudaria bastante, porém caso não seja possível farei de tudo para adquirir conhecimento a respeito das sintaxes e funcionalidades do MongoDB o mais rápido possível para tentar realizar o desafio. 

Aguardo e desde já agradeço.

**Comment by fhlpassis** [comment]
Sim, tudo bem.
